spring:
  main:
    lazy-initialization: false
    log-startup-info: true
    devtools:
      add-properties: false
      remote:
        restart:
          enabled: false
  aop:
      proxy-target-class: true

  datasource:
    url: jdbc:mysql://localhost:3306/vietnam_japan_market
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL8Dialect
        enable_lazy_load_no_trans: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  web:
    resources:
      static-locations: classpath:/static/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 45MB
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: phd30029001@gmail.com
    password: kvmccpyzsztikzho
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
aws:
  bucket:
    name: vietnamjapanmarketbucket
  region: ap-southeast-1
  accessKey: AKIAU6VTTYKZLHQZFO5J
  secretKey: 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
server:
  address: 0.0.0.0
  servlet:
    session:
      cookie:
        name: JSESSIONID
        same-site: Lax
        http-only: true
        secure: false
      timeout: 60m
  port: 8080
  error:
    include-stacktrace: always
    include-exception: true
    include-message: always
vnpay:
  tmnCode: 41LRT5WB
  hashSecret: S3J1BIDEMYA6KYWRU82T6ZFJZO2TF6J6
  paymentUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
logging:
  level:
    org.springframework.scheduling: DEBUG
    com.ecommerce.g58: DEBUG
